run: mixmc-rlmtest
version: "2012-10-16"

star_minmag: 18
star_maxmag: 20

cutout_size: 28
seg_padding: 5

psf_models: ['gmix2']

# should be 'random', 'mean', 'median'
psf_interp: 'median'

fitstyle: 'lm'
fitmodel: ['gexp','gdev']

shear_s2n_min: 10

# not yet implemented
#gprior_type: 'fits-vs-mag-gexponly'
gprior_type: null

# draw the g1,g2 starting points from the gprior
# not yet implemented
#draw_gprior: true

# for filling areas not in object with noise
seed: 3117

comment: |
    lm fitter
