run: mixmc-r01
version: "2012-10-16"

star_minmag: 18
star_maxmag: 20

cutout_size: 25

ngauss_psf: 2
em_maxiter: 10000
em_tol: 1.0e-6


# step and burnin are *per walker*
nwalkers: 20
nstep: 200
burnin: 400
mca_a: 3.0

fitmodel: ['gdev','gexp']

# draw the g1,g2 starting points from the gprior
draw_gprior: true

# for filling areas not in object with noise
seed: 3486
