run: mixmc-rtest
version: "2012-10-16"

star_minmag: 18
star_maxmag: 20

cutout_size: 28
seg_padding: 5

psf_models: ['admom']
psf_admom_nsub: 16

cen_prior: 1.0e-3

em_maxiter: 10000
em_tol: 1.0e-6

# should be 'random', 'mean', 'median', 'median-render'
psf_interp: 'median-render'
psf_render_fit_model: 'gmix2'

# step and burnin are *per walker*
# 40 guarantees convergence but 20 works as well for the most part
nwalkers: 20
nstep: 200
burnin: 400

iter: true
mca_a: 3.0 # about 35% acceptance

fitmodel: ['gexp','gdev']

shear_s2n_min: 10

gprior_type: 'fits-vs-mag-gexponly'


# draw the g1,g2 starting points from the gprior
draw_gprior: true

# for filling areas not in object with noise
seed: 897

comment: |
    do admom with sub-pixel and then render psf at the correct pixel
    gmix2 psf
