run: mixmc-r22
version: "2012-10-16"

star_minmag: 18
star_maxmag: 20

cutout_size: 28
include_all_seg: false

psf_models: ['gmix1']

# should be 'random', 'mean', 'median'
psf_interp: 'median'

# step and burnin are *per walker*
# 40 guarantees convergence but 20 works as well for the most part
nwalkers: 20
nstep: 200
burnin: 400

iter: true
mca_a: 3.0 # about 35% acceptance

fitmodel: ['gexp','gdev']

shear_s2n_min: 10

gprior_type: 'fits-vs-mag'
Tprior_type: 'fits-vs-mag'

# draw the g1,g2 starting points from the gprior
draw_gprior: true

# for filling areas not in object with noise
seed: 6671

comment: |
    same as r21 but with Tprior
    - Now separate priors for dev and exp.
    - Using the GPriorExp model for both.  
    - Do not include entire seg area.
    - gmix1 psf
    - median
