run: mixmc-r05
version: "2012-10-16"

star_minmag: 18
star_maxmag: 20

cutout_size: 25

psf_models: ['em1','em2']
em_maxiter: 10000
em_tol: 1.0e-6

# should be 'random', 'mean', 'median'
psf_interp: 'median'

# step and burnin are *per walker*
nwalkers: 40
nstep: 200
burnin: 400

burnin0: 400
burnin_s2n0: 50
burnin_slope: 5.0

iter: true
mca_a: 3.0 # about 35% acceptance
#mca_a: 4.5

fitmodel: ['gdev','gexp']

shear_s2n_min: 10
#shear_s2n_min: 90
# point at which we increase the burnin to burnin2
shear_s2n_change: 50

gprior_type: 'fits'
gprior_pars_exp: [1.0, 13.68, 0.051, 0.87]
gprior_pars_dev: [1.0, 8.0, 9.5e-7]


# draw the g1,g2 starting points from the gprior
draw_gprior: true

# for filling areas not in object with noise
seed: 4272

comment: |
    twice the number of walkers as previous
    seems to stabilize everything
