# smaller cutout
run: umom-r04
version: "2012-10-16"

star_minmag: 18
star_maxmag: 20

cutout_size: 28
use_seg: false
include_all_seg: false
isolated: false

# for getting <e^2>
gprior_type: 'fits-vs-mag'

#uw_nsig: 4.0
#uw_min_pixels: 4

# for filling areas not in object with noise
seed: 6106

comment: |
    no seg cuts at all
