# used single truncated gauss for bd frac prior
# don't use!

version: "003"
models: [bdf]

nwalkers: 80
#burnin: 2000
burnin: 400
nstep: 100
mca_a: 3.0
#mca_a: 2.0

min_arate: 0.25
#min_arate: 0.40
ntry: 5
