run: "gmix-r03"

filter: "r"

# 2 fully free gaussians
# 3 works even better but takes 4000 iterations
# as compared to about 400 for 2
psf_model: 'em2'

obj_fitter: 'lm'
obj_models: ['gexp','gdev']

admom_ntry: 4
psf_em_ntry: 4
obj_lm_ntry: 4

max_cmodelmag_r: 22.0
# minimum adaptive moment s/n
min_s2n: 10

make_plots: false
make_psf_plots: false

minscore: 0.1

skipids: [14620301302090836]

verbose: false
