run: "gmix-r01"

filter: "r"

psf_model: 'gmix3'

obj_fitter: 'lm'
obj_models: ['gexp','gdev']

admom_ntry: 4
psf_lm_ntry: 4
obj_lm_ntry: 4

nwalkers: 20
burnin: 200
nstep: 200
mca_a: 3
iter: true

max_cmodelmag_r: 22.0
# minimum adaptive moment s/n
min_s2n: 10

make_plots: false
make_psf_plots: false

minscore: 0.1
