# r01 means r-band run number 01
run: "gmix-r01"

filter: "r"


# ignored for now
psf_model: 'gmix3'

# ignored for now
obj_models: ['gexp','gdev']
obj_fitters: ['lm','mcmc']


admom_ntry: 4
psf_lm_ntry: 4
obj_lm_ntry: 4

nwalkers: 20
burnin: 200
nstep: 200
mca_a: 3
iter: true

max_cmodelmag_r: 22.0

make_plots: false
make_psf_plots: false
