bin_info:
    - label: '$\lambda  > 5  z \in  [0.2,0.4]'
      bins: [ ["lambda_chisq", [5.0, 1.0e6], "()"],
              ["z_lambda", [0.2, 0.4], "()"] ]
    - label: '$\lambda  > 5  z \in  [0.4,0.8]'
      bins: [ ["lambda_chisq", [5.0, 1.0e6], "()"],
              ["z_lambda", [0.4, 0.8], "()"] ]
