bin_info:
    - label: '$\lambda  \in [5,20] z \in  [0.2,0.3]'
      bins: [ ["lambda_chisq", [5.0, 20], "()"],
              ["z_lambda", [0.2, 0.3], "()"] ]

    - label: '$\lambda  \in [5,20]  z \in  [0.3,0.4]'
      bins: [ ["lambda_chisq", [5.0, 20], "()"],
              ["z_lambda", [0.3, 0.4], "()"] ]

    - label: '$\lambda  \in [5,20]  z \in  [0.4,0.6]'
      bins: [ ["lambda_chisq", [5.0, 20], "()"],
              ["z_lambda", [0.4, 0.6], "()"] ]

    - label: '$\lambda  \in [5,20]  z \in  [0.6,0.8]'
      bins: [ ["lambda_chisq", [5.0, 20], "()"],
              ["z_lambda", [0.6, 0.8], "()"] ]

    - label: '$\lambda  > 20  z \in  [0.2,0.3]'
      bins: [ ["lambda_chisq", [20, 1.0e+06], "()"],
              ["z_lambda", [0.2, 0.3], "()"] ]

    - label: '$\lambda  > 20  z \in  [0.3,0.4]'
      bins: [ ["lambda_chisq", [20, 1.0e+06], "()"],
              ["z_lambda", [0.3, 0.4], "()"] ]

    - label: '$\lambda  > 20  z \in  [0.4,0.6]'
      bins: [ ["lambda_chisq", [20, 1.0e+06], "()"],
              ["z_lambda", [0.4, 0.6], "()"] ]

    - label: '$\lambda  > 20  z \in  [0.6,0.8]'
      bins: [ ["lambda_chisq", [20, 1.0e+06], "()"],
              ["z_lambda", [0.6, 0.8], "()"] ]
