# [0.2,0.3]
# [0.3,0.4]
# [0.4,0.6]
# [0.6,0.8]

bin_info:
    - label: '$\lambda  > 5  z \in  [0.2,0.3]'
      bins: [ ["lambda_chisq", [5.0, 1.0e+06], "()"],
              ["z_lambda", [0.2, 0.3], "()"] ]

    - label: '$\lambda  > 5  z \in  [0.3,0.4]'
      bins: [ ["lambda_chisq", [5.0, 1.0e+06], "()"],
              ["z_lambda", [0.3, 0.4], "()"] ]

    - label: '$\lambda  > 5  z \in  [0.4,0.6]'
      bins: [ ["lambda_chisq", [5.0, 1.0e+06], "()"],
              ["z_lambda", [0.4, 0.6], "()"] ]

    - label: '$\lambda  > 5  z \in  [0.6,0.8]'
      bins: [ ["lambda_chisq", [5.0, 1.0e+06], "()"],
              ["z_lambda", [0.6, 0.8], "()"] ]
