# [0.2,0.3]
# [0.3,0.4]
# [0.4,0.6]
# [0.6,0.8]

bin_info:
    - label: '$z \in  [0.2,0.3]'
      bins: [ ["z", [0.2, 0.3], "()"] ]

    - label: '$z \in  [0.3,0.4]'
      bins: [ ["z", [0.3, 0.4], "()"] ]

    - label: '$z \in  [0.4,0.6]'
      bins: [ ["z", [0.4, 0.6], "()"] ]

    - label: '$z \in  [0.6,0.8]'
      bins: [ ["z", [0.6, 0.8], "()"] ]
