bin_info:
    - label: '$\lambda  \in [5,20]  z \in  [0.2,0.4]'
      bins: [ ["lambda_chisq", [5.0, 20.0], "()"],
              ["z_lambda", [0.2, 0.4], "()"] ]

    - label: '$\lambda  \in [5,20]  z \in  [0.4,0.8]'
      bins: [ ["lambda_chisq", [5.0, 20.0], "()"],
              ["z_lambda", [0.4, 0.8], "()"] ]


    - label: '$\lambda  > 20  z \in  [0.2,0.4]'
      bins: [ ["lambda_chisq", [20.0, 1.0e+06], "()"],
              ["z_lambda", [0.2, 0.4], "()"] ]

    - label: '$\lambda  > 20  z \in  [0.4,0.8]'
      bins: [ ["lambda_chisq", [20.0, 1.0e+06], "()"],
              ["z_lambda", [0.4, 0.8], "()"] ]
