lcat_name: "redmapper-6.2.12"

cosmo_vers: "cosmo-01"

nchunk: 1

nbin: 21
rmin: 0.02
rmax: 35.15

zmin: 0.1
zmax: 0.9

# this is "eq" or "sdss"
mask_style: "equatorial"
mask_type: "healpix"
mask_file: "/astro/u/esheldon/masks/des/neff/sva1_gold_1.0_nside4096-64_ring_i_neff.fits"
mask_ellip_max: 0.05

index_col:  "mem_match_id"
ra_col:     "ra"
dec_col:    "dec"
z_col:      "z_lambda"
lambda_col: "lambda_chisq"
