comments: |
    max rad 5 mpc
    this is peters mask from the actual density of sources

lcat_name: "redmapper-6.3.3-lgt05"
type: "lenses"

cosmo_vers: "cosmo-01"

nchunk: 1

nbin: 9
rmin: 0.08
rmax: 5.0

zmin: 0.2
zmax: 0.8

# corresponds to a config file
mask_vers: "mask-ngmix011-v15"

index_col:  "mem_match_id"
ra_col:     "ra_cent"
dec_col:    "dec_cent"
cen_index:  1
z_col:      "z_lambda"
lambda_col: "lambda_chisq"

jackreg_col: "jack_region100"
