comments: "uniform in z, drawn from neff map i for ra,dec"

lcat_name: "rand-spte01"
type: "random"

cosmo_vers: "cosmo-01"

nchunk: 50

nbin: 17
rmin: 0.055
rmax: 35.15

zmin: 0.2
zmax: 0.8

# this is "eq" or "sdss"
mask_style: "equatorial"
mask_type: "healpix"
mask_file: "/astro/u/esheldon/masks/des/neff/sva1_gold_1.0_nside4096-64_ring_i_neff.fits"
mask_ellip_max: 0.05

index_col:  "rand_index"
ra_col:     "ra"
dec_col:    "dec"
#z_col:      "ztrue"
z_col:      "z"

# for matching to lens catalogs.
# Can be "z" or "selection", or "selection-and-z"
match_type: "z"

#zmatch_method: "weight"
zmatch_method: "remove"
