# same as rm007 but 50 chunks
lcat_name: "redmapper-6.3.3-random-lgt05"
type: "random"

cosmo_vers: "cosmo-01"

nchunk: 50

nbin: 14
rmin: 0.055
rmax: 11.5

zmin: 0.2
zmax: 0.8

# corresponds to a config file
mask_vers: "mask-ngmix011-v15"

# I added this index
index_col:  "rand_index"

ra_col:     "ra"
dec_col:    "dec"
z_col:      "z_lambda"

# I renamed
lambda_col: "lambda_chisq"

# they are all unity in this catalog
#extra_weight_col: "rand_weight"

# for matching to lens catalogs.
# Can be "z" or "selection", or "selection-and-z"
#match_type: "selection-and-z"
match_type: "selection"

zmatch_method: "weight"

jackreg_col: "jack_region100"
