comments: "6.2.15, zmask randoms, lambda > 5, limited to spt-e subarea"

lcat_name: "redmapper-6.2.15-random-zmask-lgt05-subarea"
type: "random"

cosmo_vers: "cosmo-01"
mask_vers: "mask-sva1-i-01"

nchunk: 25

nbin: 17
rmin: 0.055
rmax: 35.15

zmin: 0.2
zmax: 0.8


index_col:  "rand_index"
ra_col:     "ra"
dec_col:    "dec"
z_col:      "z_lambda"
lambda_col: "lambda_chisq"

# they are all unity in this catalog
#extra_weight_col: "rand_weight"

# for matching to lens catalogs.
# Can be "z" or "selection", or "selection-and-z"
match_type: "selection-and-z"

zmatch_method: "weight"

#jackreg_col: "jack_region40"
#jackreg_col: "jack_region60"
#jackreg_col: "jack_region80"
jackreg_col: "jack_region100"
