# my randoms cut to spte subarea
lcat_vers: "rcat-rm005subarea"

# ngmix009, pz v0.1, skynet_mag_auto, Matt's cuts
scat_vers: "scat-ngmix001"

# this is used in xshear, not for the maskflags
healpix_nside: 64

# only applies if using point photoz
#zdiff_min: 0.2
