comments: |
    redmapper-6.3.3-random-lgt05.fits

lcat_vers: "rcat-rm008"

scat_vers: "scat-ngmix-skynet002"

# this is used in xshear, not for the maskflags
healpix_nside: 64

# only applies if using point photoz
#zdiff_min: 0.2
