# redmapper 6.2.12 erase with spt-e ra,dec cut
# also bug fix in xshear putting too many objects in lower and upper bins
lcat_vers: "rcat-rm001"

# ngmix009 reduced, pz v0.1, skynet_mag_auto
# matt's cuts
scat_vers: "scat-ngmix001"

# this is used in xshear, not for the maskflags
healpix_nside: 64

# only applies if using point photoz
#zdiff_min: 0.2
