# redmapper 6.2.12 with spt-e ra,dec cut
# also bug fix in xshear putting too many objects in lower and upper bins
lcat_vers: "lcat-rm001"

# ngmix009, pz v0.1.5, zebra, Matt's cuts
scat_vers: "scat-ngmix003"

# this is used in xshear, not for the maskflags
healpix_nside: 64

# only applies if using point photoz
#zdiff_min: 0.2
