# redmapper 6.2.15, lambda > 5 with spt-e ra,dec cut
# also bug fix in xshear putting too many objects in lower and upper bins
lcat_vers: "lcat-rm004subarea"

# ngmix009, pz v0.1, skynet_mag_auto, Matt's cuts
scat_vers: "scat-ngmix001"

# this is used in xshear, not for the maskflags
healpix_nside: 64

# only applies if using point photoz
#zdiff_min: 0.2
