comment: |
    Using v15 (if v16 comes ngmix will be the same)
    skynet mag auto p(z) v0.1.7 
    ngmix011-v15b-all
        - ubermem not removed
    peters mask from the actual density of sources

scat_name: "ngmix011-v15b-all"
scat_table: "ngmix011"

cosmo_vers: "cosmo-01"

# not yet used
mask_vers: "mask-ngmix011-v15"
mask_type: "healpix"

pz_vers: "v0.1.7"
pz_type: "skynet_mag_auto"

shear_style: "lensfit"
scinv_style: "interp"
scinv_col: "scinv"
scinv_flags_col: "scinv_flags"

#minus_e1: True
minus_e1: False
minus_e2: False

# support this as well in the future
#scinv_style: 'point'
#z_col: 'zp'

# the catalog is already selected in many ways

ra_col: "ra"
dec_col: "dec"

e1_col: "exp_e_1"
e2_col: "exp_e_2"
e_cov_11_col: "exp_e_cov_1_1"
e_cov_22_col: "exp_e_cov_2_2"

e1sens_col: "exp_e_sens_1"
e2sens_col: "exp_e_sens_2"

s2n_col: "exp_s2n_r"
T_col: "exp_T_r"
psf_T_col: "psfrec_T"

# cuts
s2n_min: 15.0
Trat_min: 0.15

# currently (June 5 2015) defined as three bins of equal
# number density ngmix sources in the range 0.3<z<1.3
# where z is the skynet mean z over the p(z)
keep_photoz_bins: [0,1,2]

shapenoise: 0.22
