comment: |
    skynet p(z) v0.1.5
    trimmed to spt-e
    Matts new cuts

    trim to mask

scat_name: "ngmix009"

cosmo_vers: "cosmo-01"
mask_vers: "mask-sva1-i-01"

pz_vers: "v0.1.5"
pz_type: "skynet_mag_auto"

shear_style: "lensfit"
scinv_style: "interp"
scinv_col: "scinv"

# e1 only needed for old ngmix
minus_e1: True
minus_e2: False

# support this as well in the future
#scinv_style: 'point'
#z_col: 'zp'

sxflags_col: "flags_i"
mag_auto_col: "mag_auto_i"
mag_psf_col: "mag_psf_i"
class_star_col: "class_star_i"
spread_model_col: "spread_model_i"
spreaderr_model_col: "spreaderr_model_i"

ra_col: "alphawin_j2000_r"
dec_col: "deltawin_j2000_r"

flags_col: "ngmix009_exp_flags"
e1_col: "ngmix009_exp_e_1"
e2_col: "ngmix009_exp_e_2"
e_cov_11_col: "ngmix009_exp_e_cov_1_1"
e_cov_12_col: "ngmix009_exp_e_cov_1_2"
e_cov_22_col: "ngmix009_exp_e_cov_2_2"

e1sens_col: "ngmix009_exp_e_sens_1"
e2sens_col: "ngmix009_exp_e_sens_2"

arate_col: "ngmix009_exp_arate"
T_col: "ngmix009_exp_t"
Ts2n_col: "ngmix009_exp_t_s2n"
s2n_col: "ngmix009_exp_s2n_w"


# Matt's new cut on Ts2n.  Lower s/n to 10. arate up to 0.4, which is
# a negligible difference.

sg_type: "modest"
s2n_min: 10.0
Ts2n_min: 3.0
arate_range: [0.4,0.6]
