# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cpgnumpy', [dirname(__file__)])
        except ImportError:
            import _cpgnumpy
            return _cpgnumpy
        if fp is not None:
            try:
                _mod = imp.load_module('_cpgnumpy', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cpgnumpy = swig_import_helper()
    del swig_import_helper
else:
    import _cpgnumpy
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class cPgNumpy(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cPgNumpy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cPgNumpy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _cpgnumpy.new_cPgNumpy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cpgnumpy.delete_cPgNumpy
    __del__ = lambda self : None;
    def open(self, *args): return _cpgnumpy.cPgNumpy_open(self, *args)
    def use_text(self): return _cpgnumpy.cPgNumpy_use_text(self)
    def set_decorators(self, *args): return _cpgnumpy.cPgNumpy_set_decorators(self, *args)
    def set_fetch_count(self, *args): return _cpgnumpy.cPgNumpy_set_fetch_count(self, *args)
    def execute(self, *args): return _cpgnumpy.cPgNumpy_execute(self, *args)
    def write(self, filename = None): return _cpgnumpy.cPgNumpy_write(self, filename)
    def execwrite(self, *args): return _cpgnumpy.cPgNumpy_execwrite(self, *args)
    def ntuples(self): return _cpgnumpy.cPgNumpy_ntuples(self)
    def nfields(self): return _cpgnumpy.cPgNumpy_nfields(self)
    def status(self): return _cpgnumpy.cPgNumpy_status(self)
    def set_field_lengths(self, *args): return _cpgnumpy.cPgNumpy_set_field_lengths(self, *args)
    def clear_field_lengths(self): return _cpgnumpy.cPgNumpy_clear_field_lengths(self)
    def fetchall(self): return _cpgnumpy.cPgNumpy_fetchall(self)
    def clear(self): return _cpgnumpy.cPgNumpy_clear(self)
    def close(self): return _cpgnumpy.cPgNumpy_close(self)
cPgNumpy_swigregister = _cpgnumpy.cPgNumpy_swigregister
cPgNumpy_swigregister(cPgNumpy)



