# not g prior during
run: "nfit-noisefree-07"
fitter: "max"

g_prior_during: False

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

# images are "noise free" but there is some noise in the image
# and whitening has been done
noisefree: True

# noise to assume for noise free images
skynoise: 0.05

gdrun: "nbc-sva1-004"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 10000

psf_model: "em3"

psf_em_ntry: 10
psf_em_maxiter: 50000
psf_em_tol: 5.0e-6

# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"
trim_image: False
trim_nsigma: 5

#max_pars:
#    method: 'Nelder-Mead'
#    ntry: 4
#    maxiter: 4000
#    maxfev: 4000
#    ftol: 1.0e-5
#    xtol: 1.0e-5

max_pars:
    method: 'lm'
    ntry: 4
    lm_pars:
        maxfev: 4000

do_shear: False

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 1.0

use_logpars: True

# from fitting to all cosmos galaxies in galsim data
g_prior_type: "ba"
g_prior_sigma: 0.3

T_prior_type: "TwoSidedErf"
#T_prior_pars: [-0.07, 0.03, 1.0e+06, 1.0e+05]
T_prior_pars: [-7.0, 0.1, 15.5, 0.1]

counts_prior_type: "TwoSidedErf"
#counts_prior_pars: [-1.0, 0.1, 4.0e+06, 1.0e+05]
# cold have been log(counts) in 2 to 12
counts_prior_pars: [0.0, 0.1, 15.5, 0.1]

# minutes
checkpoints: [0,10,20,30,40,50,60,70,80,90,100,110]
