# uses old style names
run: "nfit-noisefree-01"
noisefree: true
# noise to assume for noise free images
skynoise: 0.05

gdrun: "nbc-sva1-001"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
# em+lm only code is faster
nper: 1000

fitter: "lm"

psf_model: "em3"

# really nail the psf
psf_em_ntry: 2000
psf_em_maxiter: 50000
psf_em_tol: 5.0e-6

# don't need to nail galaxy fit
gal_em_ntry: 200
gal_em_maxiter: 5000
gal_em_tol: 5.0e-4


# in arcsec
psf_fwhm_guess: 0.9

fit_model: "sersic"
trim_image: True

iter: True
ntry: 2

mca_a: 2.0
nwalkers: 80
#burnin: 800
#nstep: 800
burnin: 400
nstep: 100

ntry_lm: 5

do_pqr: False

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 1.0

# from fitting to all cosmos galaxies in galsim data
g_prior_type: null

T_prior_type: "flat"
T_prior_pars: [0.001, 50.0]

# we cannot use cosmos because the fluxes were rescaled
counts_prior_type: "flat"
counts_prior_pars: [1.0, 50000.0]

n_prior_type: "flat"
n_prior_pars: [0.751,5.999]

# minutes
checkpoints: [60,110]

lm_pars:
    maxfev: 300
    ftol:   1.0e-6
    xtol:   1.0e-6
    epsfcn: 1.0e-6
