# mcmc
# turb psf, guess from em
run: "nfit-15"
fitter: "mcmc"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

# images are "noise free" but there is some noise in the image
# and whitening has been done
noisefree: False

gdrun: "nbc-sva1-001"

# number per g number, index 0-1
#nf: 600
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 250

psf_model: "turb"
psf_method: 'lm'
psf_ntry: 20
psf_max_pars:
    maxfev: 4000

# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"

# guess for max like
guesser_type: "em"
gal_em_ntry: 200
gal_em_maxiter: 5000
gal_em_tol: 5.0e-4

emcee_pars:
    nwalkers: 20
    burnin: 800
    nstep: 400
    thin: 2
    a: 2.0

# lm with my covariance
max_pars:
    method: 'lm'
    ntry: 4
    cov_h: 1.0e-3
    cov_m: 5.0
    lm_pars:
        maxfev: 4000


do_shear: True

use_logpars: True

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 0.07

g_prior_type: "ba"
g_prior_sigma: 0.3
g_prior_during: True

T_prior_type: "Normal"
T_prior_pars: [-1.13, 1.00]

# tail of normal
counts_prior_type: "TruncatedNormal"
counts_prior_pars: [1.8, 2.2, 4.15, 12.0]

# minutes
checkpoints: [30,60,90,110]
