run: "sfit-noisefree-e01"
fitter: "max"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

noisefree: True

# images are "noise free" but there is some noise in the image and whitening
# has been done.  calculate from a border region

calc_weight: True

gdrun: "nbc-sva1-004"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 10000

max_pars:
    method: 'lm'
    ntry: 4
    lm_pars:
        maxfev: 4000

psf_pars:
    model: "turb"
    ntry: 20
    fwhm_guess: 0.9
    addnoise: 0.0001

model_pars:
    model: "exp"

    g_prior_type: "flat"
    g_prior_pars: [1.0]

    T_prior_type: "flat"
    T_prior_pars: [-11.5, 8.05]

    counts_prior_type: "flat"
    counts_prior_pars: [-9.2,15.0]

    cen_prior_type: "dgauss"
    cen_prior_pars: [0.4]

do_shear: True

use_logpars: True
