# test where I added setting norms right after convolution
run: "sfit-test03"
fitter: "max-s"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

noisefree: True

# images are "noise free" but there is some noise in the image and whitening
# has been done.  calculate from a border region

calc_weight: True

gdrun: "nbc-sva1-004"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 10000
#nper: 2000

psf_model: "turb"
psf_method: 'lm'
psf_ntry: 20
psf_max_pars:
    maxfev: 4000

psf_addnoise: 0.0001

# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"

# lm with my covariance
max_guesser: "T-flux-and-prior"
#max_pars:
#    method: 'nm'
#    ntry: 4
#    maxfev: 4000
#   maxiter: 4000
#    xtol: 1.0e-5
#    ftol: 1.0e-5
max_pars:
    method: 'lm'
    bestof: 1
    ntry: 4
    cov_h: 1.0e-3
    cov_m: 5.0
    lm_pars:
        maxfev: 4000

do_shear: True

use_logpars: True

# pixel scale is 0.27''
cen_width: 1.0

#g_prior_type: "cosmos-sersic"
g_prior_type: "ba"
g_prior_sigma: 0.3
g_prior_during: True

T_prior_type: "flat"
T_prior_pars: [-11.5, 8.05]

counts_prior_type: "flat"
counts_prior_pars: [-9.2, 15.0]
