run:           "lrgdes01im3shape-r01"
lens_sample:   "lrgdes01"
src_sample:    "im3shape-r01"

# for healpix
nside:         64

comment: | 

    lenses:

        sample: "lrgdes01"
        catalog: "lrg-des-sva1-gold-1.0"

    sources:
        catalog:            "im3shape-v3-gold-nn"
        band:               "r"
