run:           "rm07s08v2"
lens_sample:   "rm07"
src_sample:    "08"

# for healpix
nside:         64

comment: | 

    # using new code
    lenses:

        Red mapper
        sample: "rm07"
        catalog: "redmapper-dr8-5.10-lgt05"

    sources:
        sample:  "08"
        catalog: dr8regauss
        filter:  "r"
