run:           "proper02"
lens_sample:   "proper02"
src_sample:    "05"

# for healpix
nside:         4096

comment: | 

    lenses:
        ProPer sample, cut to z [0.05,0.4], with strict edge cuts.
        nbin 21
        r min max [0.02,36.567]
    sources:
        src r < 21.5.  Uses mean scinv as a function of lens redshift
        has scinv on grid [0.02,0.41], dz 0.015
