run:           "06"
lens_sample:   "05"
src_sample:    "04"

# for healpix
nside:         4096

comment: | 

    lenses:
        MaxBCG
        nbin 21
        r min max [0.02,36.567]
    sources:
        src r < 21.5.  Uses mean scinv as a function of lens redshift
