run:           "rmdes01im3shape-r01"
lens_sample:   "rmdes01"
src_sample:    "im3shape-r01"

# for healpix
nside:         64

comment: | 

    lenses:

        Red mapper
        sample: "rmdes01"
        catalog: "redmapper-des-5.9-lgt05"


    sources:
        catalog:            "im3shape-v3-gold-nn"
        band:               "r"
