run:           "05"
lens_sample:   "04"
cosmo_sample:  "01"
src_sample:    "04"
nbin:          21
rmin:          0.02
rmax:          36.567
nside:         4096
comment: MaxBCG, src r < 21.5  Uses mean scinv as a function of lens redshift (yaml)
