sample:             "rmand02"
catalog:            dr8rmand
filter:             ["r","i"]
# point z
sigmacrit_style:    1

pzrun:              "12"
zlmin:              0.02
zlmax:              0.41
nzl:                26

cosmo_sample: "02"

nsplit:             100

comment: | 
    Rachels catalog, all cuts already applied.
    Point z
