sample:             "08"
catalog:            dr8regauss
filter:             r
sigmacrit_style:    2
procrun:            "04"
sweeptype:          gal
pzrun:              "11"
zlmin:              0.02
zlmax:              0.41
dzl:                0.015
nzl:                27

scinv_sample: "02"

# detrending info: max rmag used in detrending
# should match this with the limit used in pzrun
# or make it lower
detrend:            true
rmag_max_detrend:   21.5

# optional additional cut in magnitude
#rmag_max: 21.5

# cuts on shape catalog (other than flags==0, mag)
Rrange:             [0.33333333333333,1.0]
erange:             [-4,4]

# number of splits to use; combine later
nsplit:             100

comment: | 

    same as 05 but with detrend of <e> vs. R

    pzrun of "11" means r < 21.5
