run: bafit-geg02r01
sim: sim-geg02

runtype: bys2n

when_prior: "after"

# need to set this for the trials to work.
seed: 2121

s2n_method: admom
s2n_fac: 160

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 400

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
s2nvals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]

# step and burnin are *per walker*
nwalkers: 20
nstep: 200 # steps per walker
burnin: 400 # burnin per walker.

# draw the g1,g2 starting points from the gprior
draw_gprior: true

# for psf in EM
em_maxiter: 5000
em_tol: 1.0e-6  # (T-Told)/T

# iterate until the auto-correlation length is satisfactory
iter: true

fitmodel: ['gexp']
# try two even though we know it is only 1
ngauss_psf: 2
mca_a: 3.0

verbose: false

comments: |
    prior after
    large psf so better smpled
    Only fitting exp to exp for simplicity
    Using GMixEMBoot for psf fitting
    Drawing walkers from the gprior
    mca_a 3.0
    "stand alone" version
    2 gauss psf
    20 walkers
