# gg09 has 100 trials, using random orient bruteforce
# i had an idea that maybe the grided theta wasn't a good
# sampling of the prior; turned out not to be true
run: bayesfit-gg09r01
sim: sim-gg09

runtype: bys2n

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 500

# this gives 0.1 spacing
n_ggrid: 19
gmin: -0.9
gmax:  0.9

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2nvals: [10,15,20,25,30,40,50,60,70,80,90,100]
#s2nvals: [1.0e+8]
#s2nvals: [10]

s2n_psf: 1.0e+8

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 1
ngauss_obj: 1

coellip_psf: true
coellip_obj: true

# currently need to set this for the trials to work.
# can perhaps instead just put a set of ellipticities 
# somewhere from which to draw
seed: 335
