run: bayesfit-gg06r01
sim: sim-gg06

runtype: bys2n

s2n_method: admom
s2n_fac: 20

# number of random ellip values to generate
nume: 1000

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

#s2nvals: [5,10,15,20,25,30,40,50,60,70,80,90,100]
#s2nvals: [1.0e+8]
s2nvals: [100]
#s2nvals: [1.0e+8]

s2n_psf: 1.0e+8

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 1
ngauss_obj: 1

coellip_psf: true
coellip_obj: true

# set to null for new seed each time. Good when adding to the cache
seed: null
