# This one with fixed noise instead of fixed s/n
# s/n corresponds to means.  Includes lensfit
# same as deg03r01 but with sim-deg01
run: "cbafit-deg05r02"

# geg indicates the object is a gaussian exponential,
# and psf is a gaussian
sim_config: "$GSIM_RING_DIR/share/sim-deg01.cfg"

# geg indicates we fit a gaussian exp with single gassian psf
mcmc_config: "$GSIM_RING_DIR/share/bafit-deg01.cfg"

# we normalize splits by split for is2n==0
desired_err: 3.0e-05
nsplit0: 13000

s2n_vals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]
