# weak priors and no trimming
# need to try with trimming as well
# maybe try sigma *=1.5 or something to fix sizes?  Or are sized right?
run: gmix-fit-dt01r05
sim: sim-dt01

# type of parametrization
ptype: Tfrac
use_jacob: false

verbose: true

# you need the + or - in exponent
s2n: 1.0e+6
s2n_psf: 1.0e+6

# high S/N needs tight priors for 4 gaussians
tight_priors: false

# we should try with higher values to see what happens
ngauss_psf: 3
ngauss_obj: 4

coellip_psf: true
coellip_obj: true

# number of trials at each s2 and ellip.  Orientations will be random
# and if s2n is > 0 above, noise added to the image
ntrial: 100

maxtry: 1
maxtry_psf: 2

# this is for the gaussian PSF fit, since admom gets gaussians too perfectly
# trying out doing this automatically as needed
randomize: true

# number of times to retry when a trial fails.  This generates
# a new trial, unlike max_retry above which retries with a 
# randomized guess
itmax: 100

# realizations of the object will be on a grid in these ranges s2 is an
# approximate size ratio relative to the PSF

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80

# number of the above to realize
nums2: 20
nume:  20

seed: 9432

#simpars:
    # looks like it might be expand_fac/image_nsub after all!
    # learn this lesson, always use a large expansion factor
    # looks like we can actually do with expand fac 24 and
    # not sigma *= 1.75, but we can surely use an expand fac
    # that is s2 dependent.  The minres we are employing works
    # for exp but not for dev apparently.
    #expand_fac_min: 16

    #expand_fac_min: 24
    #expand_fac_min: 32
    #dotrim: false
    #image_nsub: 4
