# gg03 is a ring test
run: gmix-fit-gg03r06
sim: sim-gg03

# for ring, can use a pre-cached set of images
# and just add different noise realizaions if needed
# no need for cache here, just slows things down
#use_cache: true
use_cache: false
add_to_cache: false

# type of parametrization
ptype: Tfrac
use_jacob: false

verbose: true

# you need the + or - in exponent
# log spaced sequence   5   11   22    47   100
# in andres' estimator 14.5 31.9 63.8 136.3 290
s2n: 5
s2n_psf: 1.0e+6

# we should try with higher values to see what happens
ngauss_psf: 1
ngauss_obj: 1

coellip_psf: true
coellip_obj: true

maxtry: 1
maxtry_psf: 1

# this is for the gaussian PSF fit, since admom gets gaussians too perfectly
# trying out doing this automatically as needed
randomize: true

# number of times to retry when a trial fails.  This generates
# a new trial, unlike max_retry above which retries with a 
# randomized guess
itmax: 100

# number of noise relizations per image
nrepeat: 1


# set to null for new seed each time. Good when adding to the cache
seed: null
