# gg03 is a ring test
run: gmix-fit-gg03r01
sim: sim-gg03

# for ring, always use a pre-cached set of images
# and just add different noise realizaions if needed
use_cache: true

# type of parametrization
ptype: Tfrac
use_jacob: false

verbose: true

# you need the + or - in exponent
s2n: 1.0e+6
s2n_psf: 1.0e+6

# we should try with higher values to see what happens
ngauss_psf: 1
ngauss_obj: 1

coellip_psf: true
coellip_obj: true

maxtry: 1
maxtry_psf: 1

# this is for the gaussian PSF fit, since admom gets gaussians too perfectly
# trying out doing this automatically as needed
randomize: true

# number of times to retry when a trial fails.  This generates
# a new trial, unlike max_retry above which retries with a 
# randomized guess
itmax: 100

# realizations of the object will be on a grid in these ranges s2 is an
# approximate size ratio relative to the PSF

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80

# number of the above to realize
nums2: 20
nume:  20

# set to null for new seed each time. Good when adding to the cache
seed: null
