# dt02 is a ring test
run: gmix-fit-dt02r03
sim: sim-dt02

# we will use all the s2 values from the sim, a set of s/n values and a single
# ellip value
runtype: bys2n

s2n_method: matched
s2n_fac: 4

# this cuts size in half
retrim: true
retrim_fluxfrac: 0.9973
# when calculating s/n for adding noise, use an aperture
# corresponding to this integrated flux value
#s2ncalc_fluxfrac: 0.95

ie: 19 # 0.80
mins2n: 5
maxs2n: 100
nums2n: 20  # still 20*20=400

s2n_psf: 1.0e+8

use_cache: true
add_to_cache: false

# type of parametrization
ptype: Tfrac
use_jacob: false

verbose: true

# we should try with higher values to see what happens
ngauss_psf: 3
ngauss_obj: 4

coellip_psf: true
coellip_obj: true

maxtry: 2
maxtry_psf: 1

# this is for the gaussian PSF fit, since admom gets gaussians too perfectly
# trying out doing this automatically as needed
randomize: true

# number of times to retry when a trial fails.  This generates
# a new trial, unlike max_retry above which retries with a 
# randomized guess
itmax: 100

# set to null for new seed each time. Good when adding to the cache
seed: null
