run: gmix-fit-gg15r01
sim: sim-gg15

runtype: bys2n

generic_prior: true

s2n_method: admom
s2n_fac: 160

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 500

seed: 3461

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2nvals: [10000]

s2n_psf: 1.0e+8

use_cache: false
add_to_cache: false

verbose: false

fitmodel: ['coellip']
ngauss_psf: 1

em_maxiter: 5000
em_tol: 1.0e-6  # (T-Told)/T
