run: gmix-fit-gg15r01
sim: sim-gg15

runtype: bys2n

generic_prior: true

s2n_method: admom
s2n_fac: 320

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 400

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2nvals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]

s2n_psf: 1.0e+8

use_cache: false
add_to_cache: false

verbose: false

fitmodel: ['coellip']
psf_fitter: 'lm'
ngauss_psf: 1

em_maxiter: 5000
em_tol: 1.0e-6  # (T-Told)/T
