# gg08 has 100 in ring
run: mcbayes-gg08r02
sim: sim-gg08

runtype: bys2n

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 500

#nstep: 6400 # minimum number of steps
#burnin: 1000 # eventually we will figure this out on the fly
nstep: 4000 # minimum number of steps
burnin: 400 # eventually we will figure this out on the fly

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2nvals: [5,10,15,20,25,30,40,50,60,70,80,90,100]

s2n_psf: 1.0e+8

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 1
ngauss_obj: 1

coellip_psf: true
coellip_obj: true

# currently need to set this for the trials to work.
# can perhaps instead just put a set of ellipticities 
# somewhere from which to draw
seed: 113
