run: mcbayes-get02r02r03
sim: sim-get02

runtype: bys2n

# need to set this for the trials to work.
seed: 8015

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 100

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
s2nvals: [10,15,20,25,30,40,50,60,70,80,90,100]

fixcen: false
fixT: false

# step and burnin are *per walker*
nwalkers: 20
nstep: 200 # steps per walker
burnin: 200 # burnin per walker.

Tprior: false
Twidthfrac: null
eta: false
logT: false
mca_a: 2.0

when_prior: "after"
margamp: false

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 3
fitmodel: 'gexp'

coellip_psf: true
coellip_obj: true

comments: |
    sim-gexp02 is 6 gaussians
    This one prior after and keeping cov on likelihood only
    as cov0
    no prior on T
