run: mcbayes-get04r01r02r03r04
sim: sim-get04

runtype: bys2n

# need to set this for the trials to work.
seed: 6654

s2n_method: admom
s2n_fac: 40

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 600

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
s2nvals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]

fixcen: false
fixT: false

# step and burnin are *per walker*
nwalkers: 20
nstep: 200 # steps per walker
burnin: 400 # burnin per walker.

Tprior: false
Twidthfrac: null
logT: false
eta: false

iter: true

when_prior: "during"
margamp: false

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 3
fitmodel: 'gexp'

coellip_psf: true
coellip_obj: true

mca_a: 2.0

comments: |
    Doing more s2 compared to get03
