# for averaging with gg10r11
run: mcbayes-gg08r04
sim: sim-gg08

# need to set this for the trials to work across all splits
# of the ring.
seed: 2211

runtype: bys2n

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 500

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
s2nvals: [10,15,20,25,30,40,50,60,70,80,90,100]

fixcen: true
fixT: false

# step and burnin are *per walker*
nwalkers: 10
nstep: 100 # steps per walker
burnin: 400 # burnin per walker.

# this is the difference from gg08r03
when_prior: "during"

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 1
ngauss_obj: 1

coellip_psf: true
coellip_obj: true


