run: mixmc-gdt03r02
sim: sim-gdt03

runtype: bys2n

# need to set this for the trials to work.
seed: 1884

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 100

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
s2nvals: [40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400,500,600,700]

# step and burnin are *per walker*
nwalkers: 80
nstep: 200 # steps per walker
burnin: 400 # burnin per walker.

# iterate until the auto-correlation length is satisfactory
iter: true

verbose: false

ngauss_psf: 3
ngauss_obj: 3
onedelta: true

mca_a: 2.0

comments: |
    80 walkers instead of 20
