
run: "ngmix-eg01r33"
sim: "nsim-eg01"

fit_model: "exp"

nwalkers: 80
burnin:   400
nstep:    200
mca_a:    3.0

# we normalize splits by split for is2n==0
desired_err: 2.0e-05
nsplit0: 60000

s2n_vals: [ 15, 21, 30, 42, 60, 86, 122, 174, 247, 352, 500] 

label: '$exp \sigma_{gal}/\sigma_{PSF}=2$'
