
name: sim-et07

orient: ring
nring: 100

# we can trim later
dotrim: false

psfmodel: turb
psf_fwhm: 3.3

objmodel: exp

shear: [0.02,0.00]

mins2: 0.5
maxs2: 2.0
nums2: 4

mine:  0.05
maxe:  0.80
nume:  8
