# different gprior parameters
name: sim-gg15

orient: ring
nsplit: 300

dotrim: false

psfmodel: gauss
psf_sigma: 1.414
psf_ellip: 0.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gauss

shear: [0.01,0.0]

mins2: 0.5
maxs2: 0.5
nums2: 1

# gprior parameters from BA
gsigma: 0.3

comments: |
    BA13
