name: sim-gg09

orient: ring
nring: 100

dotrim: false

psfmodel: gauss
psf_sigma: 1.4
psf_ellip: 0.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gauss

# random orientation will be chosen.
shearmag: 0.04
# gaussian random number will be added to the magnitude
# trying to see if we can shake loose some of the biases
shearwidth: 0.01

mins2: 0.5
maxs2: 2.0
nums2: 4

A: 12.25
B: 0.03
C: 0.45
D: 13.

comments: |

    trying randomly oriented shear
