# I cached this but didn't need to: faster to generate on the fly
name: sim-gg04

orient: ring
nring: 100

psfmodel: gauss
psf_sigma: 1.4
psf_ellip: 0.0

objmodel: gauss

#
# an applied shear!
#
shear: [0.01,-0.01]

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80
nums2: 20
nume:  20


comments: |

    gauss obj, gauss psf, low res, analytic convolutions
    applied shear in e1 direction
