name: sim-dt01

#
# PSF parameters.
#

psfmodel: turb
# this is 1.3'' SDSS or 0.9'' DES
# sigma for gmix fit seems to be about 3.3/1.68 = ~2
psf_fwhm: 3.3

#
# Object model
#
objmodel: dev

comments: |

    exp obj, turbulent psf, low res
