name: sim-edg02

#
# PSF parameters.
#

psfmodel: dgauss
psf_sigma: 1.4
psf_e1: 0.05
psf_e2: 0.05

psf_sigrat: 2.3
psf_cenrat: 0.09

#
# Object model
#
objmodel: exp

comments: |

    exp obj, elliptical dgauss psf, low res
