name: sim-gbdcg01

orient: ring
#nsplit: 300
# using 200 so will fit in queue
nsplit: 200

dotrim: false

psfmodel: gauss

# this corresponds to 1.4 sigma in pixels
Tpsf: 3.9
psf_e1: 0.0
psf_e2: 0.0

objmodel: gbdc
frac_dev: 0.4
Tfrac_dev: 0.4

shear: [0.01,0.0]

mins2: 0.5
maxs2: 0.5
nums2: 1

# gprior parameters from BA
gsigma: 0.3

comments: |
    BA13 stuff
