name: sim-gg06

orient: ring
nring: 20

dotrim: false

psfmodel: gauss
psf_sigma: 1.4
psf_ellip: 0.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gauss

shear: [0.01,0.0]

mins2: 0.5
maxs2: 2.0
nums2: 4

comments: |

    gauss obj, gauss psf, low res, analytic convolutions
    applied shear in e1 direction

    this one is new where we generate the total ellipticities and s2 separately
