name: sim-get08

dotrim: false

orient: ring

psfmodel: gturb

# this corresponds to 1.4 sigma in pixels
Tpsf: 3.9
psf_e1: 0.0
psf_e2: 0.0

objmodel: gexp

shear: [0.04,0.00]

#mins2: 0.05
#maxs2: 2.05
#nums2: 6
mins2: 0.5
maxs2: 2.0
nums2: 4



gprior_type: 'round'

comments: |
    using for stacking
