# using BA13 gprior because it is twice differentiable
name: sim-geg02

orient: ring
nring: 100

dotrim: false

psfmodel: gauss

# 3.9 this corresponds to 1.4 sigma in pixels
Tpsf: 16.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gexp

shear: [0.04,0.0]

mins2: 0.5
maxs2: 2.0
nums2: 4

# gprior parameters from BA
gsigma: 0.3

comments: |
    BA13 stuff
