# ring test
name: sim-edg11

orient: ring
nring: 100

psfmodel: dgauss
psf_sigma: 1.4
psf_e1: 0.00
psf_e2: 0.00

psf_sigrat: 2.3
psf_cenrat: 0.09

#
# Object model
#
objmodel: exp

shear: [0.03,-0.03]

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80
nums2: 20
nume:  20


comments: |

    ring, exp obj, round dgauss psf, low res
