# different gprior parameters
name: sim-gg14

orient: ring
nring: 100

dotrim: false

psfmodel: gauss
# T = 2*1.4**2 = 3.9
psf_sigma: 6.0
psf_ellip: 0.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gauss

shear: [0.04,0.0]

mins2: 0.01
maxs2: 0.05
nums2: 1

# gprior parameters from BA
gsigma: 0.3

comments: |
    BA13
