# ring test
name: sim-edg03

#
# PSF parameters.
#

psfmodel: dgauss
psf_sigma: 1.4
psf_e1: 0.05
psf_e2: 0.05

psf_sigrat: 2.3
psf_cenrat: 0.09

#
# Object model
#
objmodel: exp

# no applied shear, for testing additive
shear: [0.0,0.0]

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80
nums2: 20
nume:  20


comments: |

    ring, exp obj, elliptical dgauss psf, zero shear, low res
