# ring
name: sim-et04

orient: ring
nring: 100

psfmodel: turb
# this is 1.3'' SDSS or 0.9'' DES
# sigma for gmix fit seems to be about 3.3/1.68 = ~2
psf_fwhm: 3.3

objmodel: exp

# we can trim later
dotrim: false
#
# an applied shear!
#
shear: [0.01,-0.01]

mins2: 0.5
maxs2: 2.0
nums2: 4

mine:  0.05
maxe:  0.80
nume:  20


comments: |

    dev obj, turb psf
    applied shear in e1 direction
