# ring
name: sim-et02

# type must be rand or ring
# default current rand
# If ring, the ntrial must be even in the run config

orient: ring

# we need to specify the number in the ring here
nring: 100

psfmodel: turb
# this is 1.3'' SDSS or 0.9'' DES
# sigma for gmix fit seems to be about 3.3/1.68 = ~2
psf_fwhm: 3.3

objmodel: exp

#
# an applied shear!
#
shear: [0.01,0.0]

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80
nums2: 20
nume:  20


comments: |

    dev obj, turb psf
    applied shear in e1 direction
