# different gprior parameters
name: sim-gg13

orient: ring
nsplit: 300

dotrim: false

psfmodel: gauss
# T = 2*1.4**2 = 3.9
psf_sigma: 1.4
psf_ellip: 0.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gauss

shear: [0.04,0.0]

mins2: 0.5
maxs2: 0.5
nums2: 1

# gprior parameters from BA
gsigma: 0.3

comments: |
    BA13
