run: stack-get05r01
sim: sim-get05

runtype: bys2n

# need to set this for the trials to work.
seed: 4124

s2n_method: admom
s2n_fac: 40

# minimum number of random ellipticities to use per split.  need decent count
# to sample the prior surface note we do pairs, so this is 600 images

min_gcount: 300

# how many different jobs running at a given s/n and s2 for the above
# min_gcount and s2n_fac
nsplit: 100

# note s2n psf lower since we stack
s2n_psf: 100.0

s2nvals: [10,20,30,40,50,60,70,80,90,100,120,150,200,250,300,350,400,500,600,700]


# don't need these
# step and burnin are *per walker*
# at least this many walkers
#nwalkers: 20
#nstep: 200 # steps per walker
#burnin: 400 # burnin per walker.

# actually using admom for now
#ngauss_psf: 1
fitmodel: 'coellip'

#mca_a: 3.0

make_plots: False

comments: |
    stacking
