# artificially set 9.4 to 10 and 20.1 to 20.0
#[5.0, 5.5, 6.7, 8.0, 10.0, 11.3, 13.6, 16.4, 20.0, 25.1, 33.1, 47.5]
#[5.5, 6.7, 8.0, 10.0, 11.3, 13.6, 16.4, 20.0, 25.1, 33.1, 47.5, 178.9]

bin_info:
    - label: '$\lambda  \in [5.0,5.5]$'
      bins: [ ["lambda_chisq", [5.0, 5.5], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [5.5,6.7]$'
      bins: [ ["lambda_chisq", [5.5, 6.7], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [6.7,8.0]$'
      bins: [ ["lambda_chisq", [6.7, 8.0], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [8.0,10.0]$'
      bins: [ ["lambda_chisq", [8.0, 10.0], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [10.0,11.3]$'
      bins: [ ["lambda_chisq", [10.0, 11.3], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [11.3,13.6]$'
      bins: [ ["lambda_chisq", [11.3, 13.6], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [13.6,16.4]$'
      bins: [ ["lambda_chisq", [13.6, 16.4], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [16.4,20.0]$'
      bins: [ ["lambda_chisq", [16.4, 20.0], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [20.0,25.1]$'
      bins: [ ["lambda_chisq", [20.0, 25.1], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [25.1,33.1]$'
      bins: [ ["lambda_chisq", [25.1, 33.1], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  \in [33.1,47.5]$'
      bins: [ ["lambda_chisq", [33.1, 47.5], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

    - label: '$\lambda  > 47.5$'
      bins: [ ["lambda_chisq", [47.5, 1.0e+06], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

