bin_info:
    - label: '$\lambda  \in [5.0,7.6]$'
      bins: [ ["lambda_chisq", [5.0, 7.6], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]



    - label: '$\lambda  \in [7.6,12.7]$'
      bins: [ ["lambda_chisq", [7.6, 12.7], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]


    - label: '$\lambda  \in [12.7,20.0]$'
      bins: [ ["lambda_chisq", [12.7, 20.0], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]


    - label: '$\lambda  > 20.0$'
      bins: [ ["lambda_chisq", [20.0, 1.0e+06], "()"],
              ["z_lambda", [0.2, 0.8], "()"] ]

