comments: "same as lcat-001 but added ra dec range limited to spt-e"

lcat_name: "redmapper-6.2.12"
type: "lenses"

cosmo_vers: "cosmo-01"

nchunk: 1

#nbin: 21
#rmin: 0.02
#rmax: 35.15
nbin: 17
rmin: 0.055
rmax: 35.15

zmin: 0.2
zmax: 0.8

# this is "eq" or "sdss"
mask_style: "equatorial"
mask_type: "healpix"
mask_file: "/astro/u/esheldon/masks/des/neff/sva1_gold_1.0_nside4096-64_ring_i_neff.fits"
mask_ellip_max: 0.05

index_col:  "mem_match_id"
ra_col:     "ra"
dec_col:    "dec"
z_col:      "z_lambda"
lambda_col: "lambda_chisq"

jackreg_col: "jack_region40"
#jackreg_col: "jack_region60"
#jackreg_col: "jack_region80"
#jackreg_col: "jack_region100"
