# redmapper 6.2.12 with spt-e ra,dec cut
lcat_vers: "lcat-002"

# ngmix009 reduced, pz v0.1, skynet_mag_auto
scat_vers: "scat-001"

# this is used in xshear, not for the maskflags
healpix_nside: 64

# only applies if using point photoz
#zdiff_min: 0.2
