#
# using sim-geg03 which has 0.04 shear
#

run: "cbafit-geg05r01"

# geg indicates the object is a gaussian exponential,
# and psf is a gaussian
sim_config: "$GSIM_RING_DIR/share/sim-geg03.cfg"

# geg indicates we fit a gaussian exp with single gassian psf
mcmc_config: "$GSIM_RING_DIR/share/bafit-geg02.cfg"

nsplit: 1000

s2n_vals: [400]

s2n_fac: 30
min_npair: 200
