#
# for generating simulation runs
#

run: "cbafit-geg01r06"

# geg indicates the object is a gaussian exponential,
# and psf is a gaussian
sim_config: "$GSIM_RING_DIR/share/sim-geg01.cfg"

# geg indicates we fit a gaussian exp with single gassian psf
mcmc_config: "$GSIM_RING_DIR/share/bafit-geg01.cfg"

nsplit: 100

s2n_vals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]

s2n_fac: 320
min_npair: 400
