#
# This one with high nsplit to test more quickly at high s/n
#

run: "cbafit-geg03r01"

# geg indicates the object is a gaussian exponential,
# and psf is a gaussian
sim_config: "$GSIM_RING_DIR/share/sim-geg01.cfg"

# geg indicates we fit a gaussian exp with single gassian psf
mcmc_config: "$GSIM_RING_DIR/share/bafit-geg01.cfg"

nsplit: 356

s2n_vals: [400]

s2n_fac: 320
min_npair: 800
