# This one with fixed noise instead of fixed s/n
# s/n corresponds to means
run: "cbafit-deg04r01"

# geg indicates the object is a gaussian exponential,
# and psf is a gaussian
sim_config: "$GSIM_RING_DIR/share/sim-deg02.cfg"

# geg indicates we fit a gaussian exp with single gassian psf
mcmc_config: "$GSIM_RING_DIR/share/bafit-deg02.cfg"

# we normalize splits by split for is2n==0
desired_err: 1.0e-05
nsplit0: 2000

s2n_vals: [200]
