# et02 is a ring test
run: deswl-gg04r04
sim: sim-gg04

runtype: byellip

use_cache: false
add_to_cache: false

s2n_fac: 10
s2n_method: matched

s2n: 1.0e+8
s2n_psf: 1.0e+8

# number of noise relizations per image
nrepeat: 1

psf_order: 10
gal_order: 8

# in number of sigma.  Applies to both objects and psf
maxaper_nsig: 4

# number of times to retry when a trial fails.  This generates
# a new trial, unlike max_retry above which retries with a 
# randomized guess
itmax: 100

# set to null for new seed each time. Good when adding to the cache
seed: null
