# this one e1e2
run: gmix-fit-dg02r01
sim: sim-dg02

# type of parametrization
ptype: e1e2
use_jacob: false
#use_jacob: true

verbose: true

s2n: 100000
s2n_psf: 100000

# we should try with higher values to see what happens
ngauss_psf: 1
ngauss_obj: 4

coellip_psf: true
coellip_obj: true

# number of trials at each s2 and ellip.  Orientations will be random
# and if s2n is > 0 above, noise added to the image
ntrial: 100

maxtry: 10
# this is for the PSF fit, since admom gets gaussians too perfectly
randomize: true

# number of times to retry when a trial fails.  This generates
# a new trial, unlike max_retry above which retries with a 
# randomized guess
itmax: 100

# realizations of the object will be on a grid in these ranges s2 is an
# approximate size ratio relative to the PSF

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80

# number of the above to realize
nums2: 20
nume:  20

seed: 87

#simpars:
#    image_nsub: 4
