# playing with very high s/n
run: mcbayes-gdt01r17
sim: sim-gdt01


runtype: bys2n

# need to set this for the trials to work.
seed: 5103

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 100

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8

s2nvals: [1.0e+4]
nwalkers: 80
nstep: 50 # steps per walker
burnin: 200 # burnin per walker.

#s2nvals: [1.0e+3]
#nwalkers: 80
#nstep: 50 # steps per walker
#burnin: 100 # burnin per walker.

#s2nvals: [100]
#nwalkers: 20
#nstep: 200 # steps per walker
#burnin: 100 # burnin per walker.

# old
#s2nvals: [100]
#nwalkers: 12
#nstep: 400 # steps per walker
#burnin: 400 # burnin per walker.


#s2nvals: [40]
#nwalkers: 20
#nstep: 200 # steps per walker
#burnin: 100 # burnin per walker.

#s2nvals: [10]
#nwalkers: 20
#nstep: 200 # steps per walker
#burnin: 100 # burnin per walker.



fixcen: false
fixT: false
when_prior: "during"
margamp: false

Tprior: false

use_cache: false
add_to_cache: false

verbose: false

ngauss_psf: 2
fitmodel: 'gdev'

coellip_psf: true
coellip_obj: true

comments: |
    100 is good enough, at least at s/n=100
    2 gauss is good enough for psf
