run: mixmc-get03r02
sim: sim-get03

runtype: bys2n

# need to set this for the trials to work.
seed: 865

s2n_method: admom
s2n_fac: 40

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 100

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
s2nvals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]

# step and burnin are *per walker*
nwalkers: 160
nstep: 200 # steps per walker
burnin: 400 # burnin per walker.

# iterate until the auto-correlation length is satisfactory
iter: true

verbose: false

fitmodel: ['coellip']

ngauss_psf: 3
ngauss_obj: 3
onedelta: true

mca_a: 2.0

comments: |
    160 walkers and 40 s2n fac for stats
