run: mixmc-get03rtest
sim: sim-get03

runtype: bys2n

# need to set this for the trials to work.
seed: 5192

s2n_method: admom
s2n_fac: 20

# minimum number of random ellipticities to use.
# need decent count to sample the prior surface
min_gcount: 100

retrim: false
retrim_fluxfrac: null
s2ncalc_fluxfrac: null

s2n_psf: 1.0e+8
#s2nvals: [1.0e+6]
s2nvals: [15,20,25,30,40,50,60,70,80,90,100,120,140,160,180,200,250,300,350,400]

# step and burnin are *per walker*
#nwalkers: 20
#nstep: 200 # steps per walker
#burnin: 400 # burnin per walker.
nwalkers: 40
nstep: 200 # steps per walker
burnin: 400 # burnin per walker.

# iterate until the auto-correlation length is satisfactory
iter: true

verbose: false

fitmodel: ['gexp','gdev']

ngauss_psf: 2

mca_a: 2.0

comments: |
    this version uses new code where we keep info for all pars
