# using BA13 gprior because it is twice differentiable
name: sim-gdg01

orient: ring
nsplit: 300

dotrim: false

psfmodel: gauss

# this corresponds to 1.4 sigma in pixels
Tpsf: 3.9
psf_e1: 0.0
psf_e2: 0.0

objmodel: gdev

shear: [0.01,0.0]

mins2: 0.5
maxs2: 2.0
nums2: 4

# gprior parameters from BA
gsigma: 0.3

comments: |
    BA13 stuff
