name: sim-dt01

#
# PSF parameters.
#

psfmodel: turb
# this is 1.3'' SDSS or 0.9'' DES
# sigma for gmix fit seems to be about 3.3/1.68 = ~2
psf_fwhm: 3.3

#
# Object model
#
objmodel: dev

# for generating the cache
mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80
nums2: 20
nume:  20


comments: |

    exp obj, turbulent psf, low res
