# devauc galaxies, gaussian psf
name: sim-dg01

#
# PSF parameters.
#

psfmodel: gauss
psf_sigma: 1.4
psf_ellip: 0.0

#
# Object model
#
objmodel: dev

#image_nsub: 4

comments: |

    dev obj, gauss psf, low res
