name: sim-et01

#
# PSF parameters.
#

psfmodel: turb
# this is 1.3'' SDSS or 0.9'' DES
psf_fwhm: 3.3

#
# Object model
#
objmodel: exp

# realizations of the object will be on a grid in these ranges s2 is an
# approximate size ratio relative to the PSF

mins2: 0.15
maxs2: 1.75
mine:  0.05
maxe:  0.80

# number of the above to realize
nums2: 20
nume:  20

comments: |

    exp obj, turbulent psf, low res
