# only doing one s2 to speed things up for EC proposal
name: sim-get03

orient: ring
nring: 100

dotrim: false

psfmodel: gturb

# this corresponds to 1.4 sigma in pixels
Tpsf: 3.9
psf_e1: 0.0
psf_e2: 0.0

objmodel: gexp

shear: [0.04,0.0]

mins2: 0.5
maxs2: 0.5
nums2: 1

# gprior parameters
A: 12.25
B: 0.2
C: 1.05
D: 13.
#A: 12.25
#B: 0.03
#C: 0.45
#D: 13.


comments: |

    6 gauss
