name: sim-edg01

#
# PSF parameters.
#

psfmodel: dgauss
psf_sigma: 1.4
psf_ellip: 0.0

psf_sigrat: 2.3
psf_cenrat: 0.09

#
# Object model
#
objmodel: exp

comments: |

    exp obj, dgauss psf, low res
