# using BA13 gprior because it is twice differentiable
name: sim-get12

orient: ring
nsplit: 100

dotrim: false

psfmodel: gturb

# this corresponds to 1.4 sigma in pixels
Tpsf: 3.9
psf_e1: 0.0
psf_e2: 0.0

objmodel: gexp

shear: [0.04,0.0]

mins2: 0.5
maxs2: 2.0
nums2: 4

# draw from distribution with this width as a fraction
# of the mean
s2_dist: "LogNormal"
#s2_dist: "Normal"
#s2_dist: null
s2_width: 0.3

# in pixels
cen_dist: "Normal"
cen_width: 0.2

# draw from distribution with this width as a fraction
# of the mean
counts_dist: "LogNormal"
#counts_dist: "Normal"
#counts_dist: null
counts_width: 0.3

# gprior parameters from BA
gsigma: 0.3

comments: |
    Added new priors
