# ring test
name: sim-edg02

orient: ring
nring: 100

# we can trim later
dotrim: false

psfmodel: dgauss
psf_sigma: 1.4
psf_e1: 0.00
psf_e2: 0.00

psf_sigrat: 2.3
psf_cenrat: 0.09

#
# Object model
#
objmodel: exp

shear: [0.01,-0.01]

mins2: 0.5
maxs2: 2.0
nums2: 4

mine:  0.05
maxe:  0.80
nume:  20

