# different gprior parameters
name: sim-gg10

orient: ring
nring: 100

dotrim: false

psfmodel: gauss
# T = 2*1.4**2 = 3.9
psf_sigma: 1.4
psf_ellip: 0.0
psf_e1: 0.0
psf_e2: 0.0

objmodel: gauss

shear: [0.04,0.0]

mins2: 0.5
maxs2: 2.0
nums2: 4

# gprior parameters
A: 12.25
B: 0.2
C: 1.05
D: 13.
#A: 12.25
#B: 0.03
#C: 0.45
#D: 13.


comments: |

    more in ring since at low s/n we see the prior

    gauss obj, gauss psf, low res, analytic convolutions
    applied shear in e1 direction

    this one is new where we generate the total ellipticities and s2 separately
