run: "stack-get10r01"
sim: "sim-get10"

runtype: "bys2n"

# need to set this for the trials to work.
seed: 4124

s2n_method: "admom"
s2n_fac: 40

# minimum number of random ellipticities to use per split.  need decent count
# to sample the prior surface note we do pairs, so this is 600 images

min_gcount: 300

# how many different jobs running at a given s/n and s2 for the above
# min_gcount and s2n_fac
nsplit: 100

# note s2n psf lower since we stack
s2n_psf: 100.0

# log spaced
s2nvals: [10,13,16,20,24,31,38,48,60,75,94,117,146,183,229,286,358,448,560,700]

fitmodel: 'coellip'

#mca_a: 3.0

make_plots: False

comments: |
    stacking
