# vim: set filetype=python :
default_version='5.1p1'

# erin sheldon's drop box
url="""
'http://dl.dropbox.com/u/7615046/openssh-%s-patched.tar.gz' % (self.version,)"""
source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'configure-make-install'

config_flags = '--with-kerberos5'

# create the ups directory after installation
create_ups="""
envPrepend(PATH,${PRODUCT_DIR}/bin)
"""
