# vim: set filetype=python :
default_version='8.12'


url="""'http://downloads.sourceforge.net/project/pcre/pcre/%s/pcre-%s.tar.gz' % (self.version,self.version)"""
source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'configure-make-install'


# for the modules system
create_module_file='''"""#%%Module
# vim: set filetype=tcl :

module-whatis	"pcre"

conflict pcre

prepend-path PATH            %s/bin
prepend-path LD_LIBRARY_PATH %s/lib
prepend-path LIBRARY_PATH    %s/lib
prepend-path C_INCLUDE_PATH  %s/include
prepend-path CPATH           %s/include
""" % tuple([self.install_dir]*5)'''



# create the ups directory after installation
create_ups="""
envPrepend(PATH,${PRODUCT_DIR}/bin)
envPrepend(C_INCLUDE_PATH,${PRODUCT_DIR}/include)
envPrepend(LD_LIBRARY_PATH,${PRODUCT_DIR}/lib)
envPrepend(LIBRARY_PATH,${PRODUCT_DIR}/lib)
"""
