# vim: set filetype=python :
default_version='8.12'


url="""'http://downloads.sourceforge.net/project/pcre/pcre/%s/pcre-%s.tar.gz' % (self.version,self.version)"""
source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'configure-make-install'


# for the modules system
create_module_file='''"""#%%Module
# vim: set filetype=tcl :

module-whatis	"pcre"

conflict pcre

set PRODUCT_DIR %s
setenv PCRE_DIR $PRODUCT_DIR

Prepend-path PATH            $PRODUCT_DIR/bin
prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
prepend-path LIBRARY_PATH    $PRODUCT_DIR/lib
prepend-path C_INCLUDE_PATH  $PRODUCT_DIR/include
prepend-path CPATH           $PRODUCT_DIR/include
""" % self.install_dir'''



# create the ups directory after installation
create_ups="""
envPrepend(PATH,${PRODUCT_DIR}/bin)
envPrepend(C_INCLUDE_PATH,${PRODUCT_DIR}/include)
envPrepend(LD_LIBRARY_PATH,${PRODUCT_DIR}/lib)
envPrepend(LIBRARY_PATH,${PRODUCT_DIR}/lib)
"""
