# vim: set filetype=python :

import distutils.sysconfig
import os

default_version='2.0.0.final.0'

url="""
'http://prdownloads.sourceforge.net/scons/scons-%s.tar.gz' % self.version"""
source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'python-setup'

create_ups="""
setupOptional("python")
envPrepend(PATH,${PRODUCT_DIR}/bin)
envPrepend(PYTHONPATH,${PRODUCT_DIR}/lib/scons-${PRODUCT_VERSION})
"""
