# vim: set filetype=python :
default_version='23.1'

url="""
'http://ftp.gnu.org/pub/gnu/emacs/emacs-%s.tar.gz' % (self.version,)"""

source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'configure-make-install'

config_flags = '--with-x --with-xft --without-gif'

# create the ups directory after installation
create_ups="""
envPrepend(PATH,${PRODUCT_DIR}/bin)
"""
