# vim: set filetype=python :
default_version='1.4.14b-stable'

url="""'http://monkey.org/~provos/libevent-%s.tar.gz' % self.version"""

source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'configure-make-install'

# create the ups directory after installation
create_ups="""
envPrepend(PATH,${PRODUCT_DIR}/bin)
envPrepend(LD_LIBRARY_PATH,${PRODUCT_DIR}/lib)
envPrepend(LIBRARY_PATH,${PRODUCT_DIR}/lib)
envPrepend(C_INCLUDE_PATH,${PRODUCT_DIR}/include)
"""
