# vim: set filetype=python :
default_version='1.2.0'

# Note I had problems downloading from the ftp site, although it seemed sporadic
url="""'http://pipeviewer.googlecode.com/files/pv-%s.tar.bz2' % self.version"""


source_type = 'tar'

# this will use the install_dir as prefix in configure
install_method = 'configure-make-install'

# create the ups directory after installation
create_ups="""
envPrepend(PATH,${PRODUCT_DIR}/bin)
"""
