run: "nfit-noisefree-04"

# images are "noise free" but there is some noise in the image
# and whitening has been done
noisefree: true
# noise to assume for noise free images
skynoise: 0.05

gdrun: "nbc-sva1-001"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
# em+lm only code is faster
nper: 50

fitter: "mcmc"

psf_model: "em3"

# really nail the psf
psf_em_ntry: 2000
psf_em_maxiter: 50000
psf_em_tol: 5.0e-6

# don't need to nail galaxy fit
gal_em_ntry: 200
gal_em_maxiter: 5000
gal_em_tol: 5.0e-4


# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"
trim_image: True
trim_nsigma: 5

mca_a: 2.0

# try a maxlike fit to start off
# if it fails, fall back to guess based on em1
iter: false
ntry: null
nwalkers: 80
burnin: 400
nstep: 800

do_pqr: False

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 1.0

# from fitting to all cosmos galaxies in galsim data
g_prior_type: "cosmos-sersic"

T_prior_type: "flat"
T_prior_pars: [0.001, 50.0]

# we cannot use cosmos because the fluxes were rescaled
counts_prior_type: "flat"
counts_prior_pars: [1.0, 50000.0]

n_prior_type: null
joint_prior_type: null

# minutes
checkpoints: [60,110]

