# isampler
# using turb fit psf, guess from em gauss
# resetting weight map
run: "nfit-noisefree-10"
fitter: "isample"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

# images are "noise free" but there is some noise in the image
# and whitening has been done
noisefree: True

# noise to assume for noise free images
calc_weight: True
#skynoise: 0.05

gdrun: "nbc-sva1-004"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 1300

psf_model: "turb"
psf_method: 'lm'
psf_ntry: 2000
psf_max_pars:
    maxfev: 4000

# in arcsec
psf_fwhm_guess: 0.9
fit_model: "exp"

guesser_type: "em"

gal_em_ntry: 200
gal_em_maxiter: 5000
gal_em_tol: 5.0e-4

isample_pars:
    sampler: "T"

    # first iteration 500, next 2000
    # 500 gives 20% slowdown, 1000 40%
    # 500 gives efficiency 0.19 +/- 0.06, 1000 0.22 +/-  0.07
    nsample: [500,2000]
    ifactor: 1.414
    df: 2.1
    min_err: [1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6]
    max_err: [1.0,1.0,1.0,1.0,1.0,1.0]

max_pars:
    method: 'lm'
    ntry: 4
    cov_h: 1.0e-3
    cov_m: 5.0
    lm_pars:
        maxfev: 4000
#        ftol:   1.0e-6
#        xtol:   1.0e-6
#        epsfcn: 1.0e-6

do_shear: True

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 1.0

use_logpars: True

# from fitting to all cosmos galaxies in galsim data
g_prior_type: "cosmos-sersic"
g_prior_during: True

T_prior_type: "TwoSidedErf"
T_prior_pars: [-12.0, 0.1, 15.5, 0.1]

counts_prior_type: "TwoSidedErf"
counts_prior_pars: [0.0, 0.1, 15.5, 0.1]

# minutes
checkpoints: [30,60,90,110]
