run: "nfit-07"
fitter: "mcmc"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

# images are "noise free" but there is some noise in the image
# and whitening has been done
noisefree: False

gdrun: "nbc-sva1-004"
#gdrun: "nbc-sva1-001"

# number per g number, index 0-1
nf: 600
#nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 250

psf_model: "em3"

# really nail the psf
psf_em_ntry: 2000
psf_em_maxiter: 50000
psf_em_tol: 5.0e-6

# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"
trim_image: False
trim_nsigma: 5

nm_pars:
    ntry: 1
    maxiter: 4000
    maxfev: 4000
    ftol: 1.0e-3
    xtol: 1.0e-3
 

# try a maxlike fit to start off
# if it fails, fall back to guess based on em1
emcee_pars:
#    nwalkers: 80
#    burnin: 400
#    nstep: 800
    nwalkers: 20
    burnin: 800
    nstep: 400
    thin: 2
    a: 2.0

do_shear: True

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 1.0

# from fitting to all cosmos galaxies in galsim data
g_prior_type: "cosmos-sersic"

#T_prior_type: "flat"
#T_prior_pars: [1.0e-05, 3500.0]
T_prior_type: "TwoSidedErf"
T_prior_pars: [-0.07, 0.03, 1.0e+06, 1.0e+05]

# we cannot use cosmos because the fluxes were rescaled
#counts_prior_type: "flat"
#counts_prior_pars: [1.0e-04,3.5e+06]
counts_prior_type: "TwoSidedErf"
counts_prior_pars: [-1.0, 0.1, 4.0e+06, 1.0e+05]

# minutes
checkpoints: [0,10,20,30,40,50,60,70,80,90,100,110]
