# guess from psf flux and priors
# no g prior during
# flat priors set to those from nfit-02

run: "sfit-noisefree-03"
fitter: "max-s"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

noisefree: True

# images are "noise free" but there is some noise in the image and whitening
# has been done.  calculate from a border region

calc_weight: True

gdrun: "nbc-sva1-001"

# number per g number, index 0-1
nf: 100

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 10000

psf_model: "turb"
psf_method: 'lm'
psf_ntry: 20
psf_max_pars:
    maxfev: 4000

psf_addnoise: 0.0001

# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"

# lm with my covariance
max_guesser: "flux-and-prior"
max_pars:
    method: 'lm'
    ntry: 4
    cov_h: 1.0e-3
    cov_m: 5.0
    lm_pars:
        maxfev: 4000

do_shear: True

use_logpars: True

# pixel scale is 0.27''
cen_width: 1.0

# this is max like only, and prior not during, so actual
# prior on shape only used for guess
g_prior_type: "ba"
g_prior_sigma: 0.3
g_prior_during: False

T_prior_type: "flat"
T_prior_pars: [-11.5, 8.05]

counts_prior_type: "flat"
counts_prior_pars: [-9.2, 15.0]
