name: tests

on:
  push:
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        pyver: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        compiler: [gcc]
        include:
            - os: macos-latest
              pyver: "3.9"
              compiler: clang
            - os: macos-latest
              pyver: "3.10"
              compiler: clang
            - os: macos-latest
              pyver: "3.11"
              compiler: clang
            - os: macos-latest
              pyver: "3.12"
              compiler: clang

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.pyver }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install deps
        run: |
            pip install matplotlib

      - name: Install code
        run: |
            pip install -e .

      - name: lint
        run: |
          pip install flake8
          flake8 espy

      - name: test
        run: |
          pip install pytest
          pytest -vv tests
