sample: "sdssrand03"

# this means it is tuned to have a redshift range surrounding
# the RedMapper ranges

catalog: redmapper-random

# this is redundant with the cosmo_sample declaration in the run file
# we have to demand consistency
cosmo_sample: "01"

# these used to be in the run file. Moved here because we need to trim lenses
# first. Make sure these match the lens sample you are correcting!
nbin:          21
rmin:          0.02
rmax:          36.567

# if true, use a strict edge cut
strict_edgecut: false


# this is chosen to be somewhat looser than redmapper, which
# is cut at 0.08 and 0.4
zmin:          0.07
zmax:          0.41

# hard edge cut, in Mpc/h
rmax_hard: 1.0

masktype: sdss

# redmapper catalog for lambda > 10 is 50000, so this is
# a factor of 100
nrand: 5000000

comment: |

    This sample is designed to be somewhat like the redmapper sample.
    Also ProPer in sample 07.
