sample: "rm07"
catalog: "redmapper-dr8-5.10-lgt05"

# this is redundant with the cosmo_sample in the scinv_sample,
# declared in the scat config
cosmo_sample: "02"

# these used to be in the run file. Moved here because we need to trim lenses
# first
nbin:          21
rmin:          0.02
rmax:          36.567

# if true, use a strict edge cut
strict_edgecut: false

# the randoms eli gave me are cut at 0.1
zmin:          0.08
zmax:          0.31

z_field: "z_lambda"
ra_field: "ra_cent"
dec_field: "dec_cent"

# when using the alternative centers ra_cent, dec_cent
# 0 is best center, 1 is next best
# for 0 this is the same as the ra,dec fields
pos_index: 1

nsplit: 1

# this is an sobjshear variable, not same as the mapname
# below
mask_type: "sdss"

mapname: "boss"
maptype: "basic"
tycho_maptype: "tycho"
maxres: 2048


