sample: "sdssrand04"

# this means it is tuned to have a redshift range surrounding
# the RedMapper ranges

catalog: "redmapper-dr8"

# this is redundant with the cosmo_sample declaration in the run file
# we have to demand consistency
cosmo_sample: "02"

# these used to be in the run file. Moved here because we need to trim lenses
# first. Make sure these match the lens sample you are correcting!
nbin:          21
rmin:          0.02
rmax:          36.567

# if true, use a strict edge cut
strict_edgecut: false

# this is chosen to be somewhat looser than redmapper, which
# is cut at 0.08 and 0.31
zmin:          0.07
zmax:          0.32

nrand: 5000000

# this is an sobjshear variable, not same as the mapname
# below
mask_type: "sdss"


mapname: "boss"
maptype: "basic"
tycho_maptype: "tycho"
maxres: 2048

comment: |

    This sample is designed to be somewhat like the redmapper dr8 5.10
