run:           "rmdes03im3r01run01"
lens_sample:   "rmdes03"
src_sample:    "im3r01"

# for healpix
nside:         64

comment: | 

    rmax ~37 Mpc
    first try with maskflags

    lenses:

        Red mapper
        sample: "rmdes01"
        catalog: "redmapper-des-5.9-lgt05"


    sources:
        catalog:            "im3shape-v3-gold-nn"
        band:               "r"
