run:           "rmrand02s08"
lens_sample:   "rmrand02"
src_sample:    "08"

# for healpix
nside:         64

comment: | 

    lenses:

        Red mapper random
        sample: "rmrand02"
        catalog: "redmapper-dr8-rand-5.10-lgt05"

    sources:
        sample:  "08"
        catalog: dr8regauss
        filter:  "r"
