run:           "sv03gmix03"
lens_sample:   "sv03"
src_sample:    "gmix03"

# for healpix
nside:         64

comment: | 

    lenses:

        SDSS voids from peter Melchior
        New ones that are actually centered

        nbin 21

        r min max [0.02,70]

    sources:
        s/n  in [40,300] sratio > sqrt(2)
