run:           "07"
lens_sample:   "06"
src_sample:    "04"

# for healpix
nside:         4096

comment: | 

    lenses:
        maxbcg random sample
        nbin 21
        r min max [0.02,36.567]
    sources:
        src r < 21.5.  Uses mean scinv as a function of lens redshift
