run:           "svrand01gmix01"
lens_sample:   "svrand01"
src_sample:    "gmix01"

# 1 is None 2 is sdss mask
mask_style:    2

# for healpix
nside:         64

comment: | 

    lenses:

        SDSS voids from peter Melchior

        nbin 21

        r min max [0.02,70]

    sources:
        gmix catalog
