run:           "sv01s05"
lens_sample:   "sv01"
src_sample:    "05"

# 1 is None 2 is sdss mask
mask_style:    2

# for healpix
nside:         64

comment: | 

    lenses:

        SDSS voids from peter Melchior

        nbin 21

        r min max [0.02,70]

    sources:
        src r < 21.5. has scinv per source on grid [0.02,0.41], dz 0.015
