run:           "rmdes02im3shape-r01"
lens_sample:   "rmdes02"
src_sample:    "im3shape-r01"

# for healpix
nside:         64

comment: | 

    rmax ~10
    In this one we calculate the moments of the source positions

    lenses:

        Red mapper
        sample: "rmdes02"
        catalog: "redmapper-des-5.9-lgt05"


    sources:
        catalog:            "im3shape-v3-gold-nn"
        band:               "r"
