run:           "rm06s08"
lens_sample:   "rm06"
src_sample:    "08"

# for healpix
nside:         64

comment: | 

    lenses:

        Red mapper
        sample: "rm06"
        catalog: "redmapper-dr8-5.10-lgt05"

    sources:
        sample:  "08"
        catalog: dr8regauss
        filter:  "r"
