run:           "rm04s06test"
lens_sample:   "rm04"
src_sample:    "06"

# 1 is None 2 is sdss mask
mask_style:    2

# for healpix
nside:         64

comment: | 

    lenses:

        Red mapper "redmapper-dr8-3.14-cen2", using 2nd best center.

        Cut to z [0.08,0.4]
        Includes the strict 1Mpc edge cut.

        nbin 21

        r min max [0.02,36.567]

    sources:
        src r < 21.5. has scinv per source on grid [0.02,0.41], dz 0.015
        same as 05 but with detrended <e> vs R
