run:           "rm03s05"
lens_sample:   "rm03"
src_sample:    "05"

# for healpix
nside:         64

comment: | 

    lenses:

        Red mapper "redmapper-dr8-3.14", cut to z [0.08,0.4]
        Includes the strict 1Mpc edge cut.

        nbin 21

        r min max [0.02,36.567]

    sources:
        src r < 21.5. has scinv per source on grid [0.02,0.41], dz 0.015
